import * as THREE from 'three'
import { OrbitControls } from 'three/addons/controls/OrbitControls.js'
import { MAP_SLOTS } from '../data/mapSlots.mjs'
import { createCreature } from './creatures.js'
import { fitCreatureModel, loadCreatureModel } from './modelLoader.js'

const rendererFor = (canvas) => { const r=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true}); r.setPixelRatio(Math.min(devicePixelRatio||1,1.7)); r.shadowMap.enabled=true; r.shadowMap.type=THREE.PCFSoftShadowMap; r.outputColorSpace=THREE.SRGBColorSpace; return r }
const lights=(s)=>{ s.add(new THREE.HemisphereLight(0xf3ffff,0x8abf9c,2)); const d=new THREE.DirectionalLight(0xffffff,2.6); d.position.set(6,9,5); d.castShadow=true; s.add(d) }
const resize=(r,c,canvas)=>{ const w=canvas.clientWidth||1,h=canvas.clientHeight||1;if(canvas.width!==Math.round(w*r.getPixelRatio())||canvas.height!==Math.round(h*r.getPixelRatio())){r.setSize(w,h,false);c.aspect=w/h;c.updateProjectionMatrix()} }
const dispose=(scene)=>scene.traverse(o=>{o.geometry?.dispose?.(); if(Array.isArray(o.material))o.material.forEach(m=>m.dispose?.());else o.material?.dispose?.()})
function loadOrFallback(id,height=3){ const holder=new THREE.Group(); const fallback=createCreature(id); holder.add(fallback); loadCreatureModel(id).then(m=>{holder.clear();holder.add(fitCreatureModel(m,height))}).catch(()=>{}); holder.userData.creatureId=id; return holder }
function iceMaterial(){ return new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{uMelt:{value:0},uTime:{value:0}},vertexShader:`varying vec3 vPos;varying vec3 vNormal;void main(){vPos=position;vNormal=normal;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform float uMelt;uniform float uTime;varying vec3 vPos;varying vec3 vNormal;float hash(vec3 p){return fract(sin(dot(p,vec3(12.9898,78.233,37.719)))*43758.5453);}void main(){float n=hash(floor(vPos*5.));float threshold=mix(-2.2,2.5,uMelt);if(vPos.y+n*.55<threshold)discard;float edge=smoothstep(.0,.18,abs((vPos.y+n*.55)-threshold));float fres=pow(1.-abs(dot(normalize(vNormal),vec3(0.,0.,1.))),2.);vec3 c=mix(vec3(.72,.94,.98),vec3(.92,1.,1.),fres);float a=mix(.56,.12,uMelt)*(1.-edge*.25);gl_FragColor=vec4(c,a);}`}) }
export function createMeltScene(canvas,progress=0,creatureId='brachiosaurus'){ const s=new THREE.Scene(),c=new THREE.PerspectiveCamera(38,1,.1,60),r=rendererFor(canvas); c.position.set(5.4,3.5,7.4);c.lookAt(0,1.7,0);lights(s); const ground=new THREE.Mesh(new THREE.CircleGeometry(4,32),new THREE.MeshStandardMaterial({color:0xe7f7f3,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;s.add(ground); const creature=loadOrFallback(creatureId,creatureId==='brachiosaurus'?3.4:2.65); creature.position.y=.05;s.add(creature); const im=iceMaterial(),ice=new THREE.Mesh(new THREE.DodecahedronGeometry(2.15,1),im);ice.position.y=1.65;ice.scale.set(1.15,1.5,.95);s.add(ice); let target=progress,dead=false,raf; const clock=new THREE.Clock(); function frame(){if(dead)return;resize(r,c,canvas);im.uniforms.uMelt.value+=(target-im.uniforms.uMelt.value)*.06;im.uniforms.uTime.value=clock.getElapsedTime();creature.rotation.y=Math.sin(clock.elapsedTime*.25)*.03;r.render(s,c);raf=requestAnimationFrame(frame)}frame();return{setProgress(v){target=Math.min(1,Math.max(0,v))},destroy(){dead=true;cancelAnimationFrame(raf);r.dispose();dispose(s)}} }
function tree(s,x,z,k=1){ const t=new THREE.Mesh(new THREE.CylinderGeometry(.1*k,.16*k,.9*k,6),new THREE.MeshStandardMaterial({color:0x9b8065,flatShading:true}));t.position.set(x,.45*k,z);s.add(t); const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(.55*k,1),new THREE.MeshStandardMaterial({color:0x6fc293,flatShading:true,roughness:.9}));crown.position.set(x,1.25*k,z);crown.castShadow=true;s.add(crown) }
function rock(s,x,z,k=1){ const m=new THREE.Mesh(new THREE.DodecahedronGeometry(.42*k,0),new THREE.MeshStandardMaterial({color:0x9aa79e,roughness:1,flatShading:true}));m.scale.set(1.35,.7,1);m.position.set(x,.18*k,z);m.castShadow=true;m.receiveShadow=true;s.add(m) }
function flower(s,x,z,color=0xfff3c4){ const stem=new THREE.Mesh(new THREE.CylinderGeometry(.012,.016,.2,5),new THREE.MeshStandardMaterial({color:0x5aa774}));stem.position.set(x,.1,z);s.add(stem); const head=new THREE.Mesh(new THREE.OctahedronGeometry(.055,0),new THREE.MeshStandardMaterial({color,flatShading:true}));head.position.set(x,.22,z);s.add(head) }
function pathStone(s,x,z,scale=.32){ const m=new THREE.Mesh(new THREE.CylinderGeometry(scale,scale*.9,.06,7),new THREE.MeshStandardMaterial({color:0xd8d4c7,roughness:1,flatShading:true}));m.position.set(x,.04,z);m.rotation.y=x*.31;s.add(m) }
export function createMeadowScene(canvas,revivedIds=[],onCreatureClick=()=>{}){ const s=new THREE.Scene();s.background=new THREE.Color(0xc8e9f4);s.fog=new THREE.Fog(0xc8e9f4,13,30);const c=new THREE.PerspectiveCamera(42,1,.1,80),r=rendererFor(canvas);c.position.set(9,7.5,11);lights(s);const controls=new OrbitControls(c,canvas);controls.target.set(0,.75,0);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=6;controls.maxDistance=17;controls.maxPolarAngle=1.25;
  const island=new THREE.Mesh(new THREE.CylinderGeometry(6.8,7.5,.92,24),new THREE.MeshStandardMaterial({color:0x9edb91,flatShading:true,roughness:.97}));island.position.y=-.42;island.receiveShadow=true;s.add(island);
  const cliff=new THREE.Mesh(new THREE.CylinderGeometry(6.25,6.9,.65,24),new THREE.MeshStandardMaterial({color:0xb8aa8f,flatShading:true,roughness:1}));cliff.position.y=-.93;s.add(cliff);
  const pond=new THREE.Mesh(new THREE.CircleGeometry(2.05,32),new THREE.MeshPhysicalMaterial({color:0x7fd4dc,transparent:true,opacity:.82,roughness:.2,metalness:0}));pond.rotation.x=-Math.PI/2;pond.position.set(1.7,.025,-1.05);s.add(pond);
  const stream=new THREE.Mesh(new THREE.PlaneGeometry(1.15,5.4,1,6),new THREE.MeshPhysicalMaterial({color:0x83d7df,transparent:true,opacity:.74,roughness:.16}));stream.rotation.x=-Math.PI/2;stream.rotation.z=-.22;stream.position.set(2.65,.03,2.2);s.add(stream);
  [[-4,-3],[4,-3],[-4,3],[4,3],[-1,4.8],[-5,.5],[5,.7]].forEach(([x,z],i)=>tree(s,x,z,.64+(i%3)*.12));
  [[-2.7,-3.5],[-4.3,-1.3],[3.8,2.8],[.4,4.4],[4.6,-.8]].forEach(([x,z],i)=>rock(s,x,z,.7+(i%2)*.25));
  for(let i=0;i<24;i++){ const a=i*.82; const rad=3.2+(i%4)*.55; flower(s,Math.cos(a)*rad,Math.sin(a)*rad,i%2?0xfff1b7:0xf7fbff) }
  for(let i=0;i<8;i++) pathStone(s,-2.1+i*.55,1.55-Math.sin(i*.7)*.22,.22+(i%2)*.04);
  const groups=[];MAP_SLOTS.forEach((slot,index)=>{if(!revivedIds.includes(slot.creatureId))return;const g=loadOrFallback(slot.creatureId,slot.creatureId==='brachiosaurus'?3.1:2.2);g.position.set(...slot.position);g.rotation.y=slot.rotationY;g.scale.setScalar(slot.scale);g.userData.creatureId=slot.creatureId;g.userData.motion={homeX:slot.position[0],homeZ:slot.position[2],phase:index*1.73,radius:.18+(index%3)*.06,speed:.075+(index%2)*.025};s.add(g);groups.push(g)});if(!groups.length){const g=loadOrFallback('brachiosaurus',3.1);g.position.set(...MAP_SLOTS[0].position);g.scale.setScalar(.72);g.userData.creatureId='brachiosaurus';g.userData.motion={homeX:MAP_SLOTS[0].position[0],homeZ:MAP_SLOTS[0].position[2],phase:0,radius:.12,speed:.06};s.add(g);groups.push(g)} const ray=new THREE.Raycaster(),p=new THREE.Vector2();const click=e=>{const rect=canvas.getBoundingClientRect();p.x=((e.clientX-rect.left)/rect.width)*2-1;p.y=-((e.clientY-rect.top)/rect.height)*2+1;ray.setFromCamera(p,c);const hit=ray.intersectObjects(groups,true)[0];if(!hit)return;let o=hit.object;while(o&&!o.userData.creatureId)o=o.parent;if(o?.userData.creatureId)onCreatureClick(o.userData.creatureId)};canvas.addEventListener('click',click);let dead=false,raf;const clock=new THREE.Clock();function frame(){if(dead)return;resize(r,c,canvas);controls.update();const t=clock.getElapsedTime();groups.forEach((g,i)=>{const m=g.userData.motion;const a=t*m.speed+m.phase;const nextX=m.homeX+Math.cos(a)*m.radius;const nextZ=m.homeZ+Math.sin(a*.9)*m.radius;const dx=nextX-g.position.x,dz=nextZ-g.position.z;g.position.x=nextX;g.position.z=nextZ;g.position.y=Math.sin(t*.72+i)*.025;if(Math.abs(dx)+Math.abs(dz)>.0001)g.rotation.y=Math.atan2(dx,dz)});r.render(s,c);raf=requestAnimationFrame(frame)}frame();return{destroy(){dead=true;cancelAnimationFrame(raf);canvas.removeEventListener('click',click);controls.dispose();r.dispose();dispose(s)}} }
